Proyects/Shop_Cofy/coffe_shop/urls.py
"""
    GLOBAL URLS 
"""
from django.contrib import admin
from django.urls import path, include

# libreria para las imagenes 
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('users/', include('users.urls')),
    path('ordes/', include('orders.urls') )
    
    # urls de las imagenes 
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Proyects/Shop_Cofy/orders/urls.py
from django.urls import path, include
from .views import MyOrderView, CreateOrderProductView

urlpatterns = [
    path('myorder/', MyOrderView.as_view(), name="my_order"),
    path('add_product', CreateOrderProductView.as_view(), name="add_product")
     
] 

Proyects/Shop_Cofy/products/urls.py
from django.urls import path
from .views import ProductFromView, ProductListView

urlpatterns = [
    path("", ProductListView.as_view(), name="all_product"),
    path('agregar/', ProductFromView.as_view(), name="add_product"),
    
]

Proyects/Shop_Cofy/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registrer",RegisterView.as_view(), name="register")
    
]

Proyects/Shop_Cofy/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

# Create your models here.

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"order {self.id} by user {self.user}"
    
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    prodeuct = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    
    def __str__(self):
        return f"Order {self.order}, product {self.prodeuct}, quantity {self.quantity}"

Proyects/Shop_Cofy/products/models.py
from django.db import models

# Create your models here.
from django.db import models


# Create your models here.
class Product(models.Model):  # nombre para el cliente final
    name = models.CharField(max_length=150, verbose_name="Nombre")
    descriptions = models.TextField(max_length=300, verbose_name="Descripoción")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio")
    url_image= models.URLField(blank=True, null= True, verbose_name="Url de la imagen", )
    avilable = models.BooleanField(default=True, verbose_name="Disponible")
    # Donde se Guardara
    photo = models.ImageField(
        upload_to="logos", null=True, blank=True, verbose_name="Logo del Producto"
    )
    date_create = models.DateTimeField(null=True,verbose_name='Fecha de creacion', auto_now_add=True)

    def __str__(self):
        return self.name 

Proyects/Shop_Cofy/orders/forms.py
from django.forms import ModelForm
from .models import OrderProduct


class OrderProductForm(ModelForm):

    class Meta:
        model= OrderProduct
        fields = [
            'prodeuct'
        ]

Proyects/Shop_Cofy/products/forms.py
from django import forms 

from .models import Product

# you form 
class ProductForm(forms.Form):
    name = forms.CharField(max_length=150, label="Inserta Nombre")
    descriptions = forms.CharField(max_length=300, label="Descripción")
    price =  forms.DecimalField(decimal_places=2,label="Precio", max_digits=10)
    url_image = forms.URLField(label="Url de la imgen", required=False, )
    avilable =  forms.BooleanField(initial=True, label="Disponible")
    photo = forms.ImageField(required=False, label="Foto")
    date_create = forms.DateTimeField(required=False,label="Fecha de creaccion ")
    
    #you save in BDD
    def save(self):
        Product.objects.create(        
            name = self.cleaned_data["name"],
            descriptions =self.cleaned_data["descriptions"],
            price =  self.cleaned_data["price"],
            url_image = self.cleaned_data["url_image"],
            avilable =  self.cleaned_data["avilable"],
            photo = self.cleaned_data["photo"],
            date_create = self.changed_data["date_create"]
        
        )

Proyects/Shop_Cofy/orders/views.py
from django.views.generic import DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Order
from .forms import OrderProductForm

# Create your views here.

class MyOrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "orders/my_order.html"
    context_object_name = "order"
    
    def get_object(self, queryset= None):
        return Order.objects.filter(is_active= True, user= self.request.user).first()
    
class CreateOrderProductView(CreateView):
    template_name = "orders/create_order_product"
    form_class = OrderProductForm
    success_url = reverse_lazy('my_order')
    
    def form_valid(self, form):
        order,_   = Order.objects.get_or_create (
            is_active = True,
            user = self.request.user,
        )
        
        form.instance.order = order
        form.instance.quantity = 1
        form.save()
        
        return super().form_valid( form)

Proyects/Shop_Cofy/products/views.py
from django.http import HttpResponse
from django.views import generic

from .forms import ProductForm
from django.urls import reverse_lazy

from .models import Product
# Create your views here.


class ProductFromView(generic.FormView):
    # indica el templeate
    template_name = "products/add_product.html"
    # require el formulario
    form_class = ProductForm
    # mensaje de confirmacion 
    success_url = reverse_lazy('all_product')


    #llama a la formulador y accede al meotodo para envair los datos a la BDD
    def form_valid(self, form) :
        form.save()
        return super().form_valid(form)
    
class ProductListView(generic.ListView):
    model = Product
    template_name = "products/all_product.html"
    context_object_name='products'

Proyects/Shop_Cofy/users/views.py
from django.shortcuts import render

# Create your views here.

from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy

class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')

Proyects/Shop_Cofy/orders/templates/orders/my_order.html
{% extends "base.html" %}

{% block content %}
<div class="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md">
    <h2 class="text-2xl font-bold mb-4">Detalles de la Orden</h2>
    <div class="mb-2">
        <span class="text-lg font-semibold">Usuario: </span>
        <span class="text-lg">{{ order.user.username|title }}</span>
    </div>
    <div class="mb-2">
        <span class="text-lg font-semibold">Fecha de la Orden: </span>
        <span class="text-lg">{{ order.order_date|date:"F j, Y H:m" }}</span>
    </div>

    <div class="mt-6">
        <h3 class="text-xl font-bold mb-2">Artículos en tu orden:</h3>
        {% for product_order in order.orderproduct_set.all %}
            <div class="flex justify-between items-center py-2 border-b">
                <div class="text-lg">{{ product_order.prodeuct.name }}</div>
                <div class="text-lg font-semibold">{{ product_order.prodeuct.price }}</div>
            </div>
        {% empty %}
            <div class="text-red-500">No hay artículos en tu orden</div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

Proyects/Shop_Cofy/products/templates/products/add_product.html
<form action= "{% url "add_product" %}" method="post" >
    {% csrf_token %}    
    {{form.as_p}}

<button type="sumbit"> Agregar </button>
</form>

Proyects/Shop_Cofy/products/templates/products/all_product.html
{% extends "base.html" %} {% block content %}

<section>
  <div class="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
    <header>
      <h2 class="text-xl font-bold text-gray-900 sm:text-3xl">
        Lista de nuestros productos
      </h2>

      <p class="mt-4 max-w-md text-gray-500">
        Este proyecto es una página web de ventas de café diseñada como una
        práctica de desarrollo web. Su objetivo es simular la interfaz de una
        tienda en línea de café, donde los usuarios pueden explorar distintos
        tipos de café, ver detalles de productos y realizar pedidos.
      </p>
    </header>

    <ul class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      {% for product in products %}
      <a href="#" class="group relative block overflow-hidden">
        <button
          class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
        >
          <span class="sr-only">{{product.name}}</span>

          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-4"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
            />
          </svg>
        </button>

        {% if product.photo %}
        <img
          src="{{product.photo}}"
          alt=""
          class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
        />
        {% else %}
        <img
          src="{{product.url_image}}"
          alt=""
          class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
        />
        {% endif %}

        <div class="relative border border-gray-100 bg-white p-6">
          <span
            class="whitespace-nowrap bg-yellow-400 px-3 py-1.5 text-xs font-medium"
          >
            {{product.date_create}}
          </span>

          <h3 class="mt-4 text-lg font-medium text-gray-900">
            {{product.name}}
          </h3>

          <p class="mt-1.5 text-sm text-gray-700">{{product.price}}</p>

          <form action= {% url "add_product " %} class="mt-4" method="post">
            {% csrf_token %}
            <input type="hidden" name="product" value = "{{product.id}}" >
            <button
              class="block w-full rounded bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
            >
              Agregar al pedido.
            </button>
          </form>
        </div>
      </a>
      {% endfor %}
    </ul>
  </div>
</section>

{% endblock content %}

Proyects/Shop_Cofy/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Coffee Shop</title>

    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    {% block content %} {% load tailwind_filters %}

    <div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
      <div class="mx-auto max-w-lg">
        <h1 class="text-center text-2xl font-bold text-indigo-600 sm:text-3xl">
          Coffee Shop
        </h1>

        <p class="mx-auto mt-4 max-w-md text-center text-gray-500">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati
          sunt dolores deleniti inventore quaerat mollitia?
        </p>

        <form
          action="#"
          class="mb-0 mt-6 space-y-4 rounded-lg p-4 shadow-lg sm:p-6 lg:p-8"
          method="post"
        >
          {% csrf_token %}
          <p class="text-center text-lg font-medium">Ingresar</p>

          {{ form|crispy }}

          <button
            type="submit"
            class="block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white"
          >
            Sign in
          </button>

          <p class="text-center text-sm text-gray-500">
            No tienes cuenta?
            <a class="underline" href="{% url "register" %}">Registrate ahora!</a>
          </p>
        </form>
      </div>
    </div>

    {% endblock content %}
  </body>
</html>

Proyects/Shop_Cofy/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Coffee Shop</title>

    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    {% block content %} {% load tailwind_filters %}

    <div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
      <div class="mx-auto max-w-lg">
        <h1 class="text-center text-2xl font-bold text-indigo-600 sm:text-3xl">
            Registrate Ahora
          </h1>

        <form
          action="#"
          class="mb-0 mt-6 space-y-4 rounded-lg p-4 shadow-lg sm:p-6 lg:p-8"
          method="post"
        >
          {% csrf_token %}
          

          {{ form|crispy }}

          <button
            type="submit"
            class="block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white"
          >
            Sign in
          </button>

          <p class="text-center text-sm text-gray-500">
            Ya tienes cuenta ?
            <a class="underline" href="{% url "login" %}" > Ingresa con tu cuenta! </a>
          </p>
        </form>
      </div>
    </div>

    {% endblock content %}
  </body>
</html>